### ISSUE TITLE
Unexpected input(s) 'tag', valid inputs are ['branch', 'from']

### ISSUE THREAD

**Issue by Devofure** [satya-500/create-branch-from-tag#1]
Hi
I get this when using your github Actions.

Unexpected input(s) 'tag', valid inputs are ['branch', 'from']

You need to update your readme if it is "from" now.
The name of the github action in the readme seems wrong too.

**Comment by Devofure** [comment]
Now I get this after I updated from "tag" to "from":

`Command failed: git rev-list -n 1 tags/1.26.0
fatal: ambiguous argument 'tags/1.26.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

**Comment by satya-500** [comment]
Hey @Devofure 

thanks for reaching me regarding this issue, now the readme file is updated. #2
